/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Sub7e4c91ab2d08f3c6RouteImport } from './routes/sub-7e4c91ab2d08f3c6'
import { Route as VlessRouteImport } from './routes/vless'
import { Route as ApiStackRouteImport } from './routes/api/stack'
import { Route as Sub7e4c91ab2d08f3c6LinksRouteImport } from './routes/sub-7e4c91ab2d08f3c6.links'
import { Route as Sub7e4c91ab2d08f3c6SbDotjsonRouteImport } from './routes/sub-7e4c91ab2d08f3c6.sb[.]json'
import { Route as Sub7e4c91ab2d08f3c6SocksDottxtRouteImport } from './routes/sub-7e4c91ab2d08f3c6.socks[.]txt'
import { Route as Sub7e4c91ab2d08f3c6SocksDotyamlRouteImport } from './routes/sub-7e4c91ab2d08f3c6.socks[.]yaml'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Sub7e4c91ab2d08f3c6Route = Sub7e4c91ab2d08f3c6RouteImport.update({
  id: '/sub-7e4c91ab2d08f3c6',
  path: '/sub-7e4c91ab2d08f3c6',
  getParentRoute: () => rootRouteImport,
} as any)
const VlessRoute = VlessRouteImport.update({
  id: '/vless',
  path: '/vless',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStackRoute = ApiStackRouteImport.update({
  id: '/api/stack',
  path: '/api/stack',
  getParentRoute: () => rootRouteImport,
} as any)
const Sub7e4c91ab2d08f3c6LinksRoute =
  Sub7e4c91ab2d08f3c6LinksRouteImport.update({
    id: '/links',
    path: '/links',
    getParentRoute: () => Sub7e4c91ab2d08f3c6Route,
  } as any)
const Sub7e4c91ab2d08f3c6SbDotjsonRoute =
  Sub7e4c91ab2d08f3c6SbDotjsonRouteImport.update({
    id: '/sb.json',
    path: '/sb.json',
    getParentRoute: () => Sub7e4c91ab2d08f3c6Route,
  } as any)
const Sub7e4c91ab2d08f3c6SocksDottxtRoute =
  Sub7e4c91ab2d08f3c6SocksDottxtRouteImport.update({
    id: '/socks.txt',
    path: '/socks.txt',
    getParentRoute: () => Sub7e4c91ab2d08f3c6Route,
  } as any)
const Sub7e4c91ab2d08f3c6SocksDotyamlRoute =
  Sub7e4c91ab2d08f3c6SocksDotyamlRouteImport.update({
    id: '/socks.yaml',
    path: '/socks.yaml',
    getParentRoute: () => Sub7e4c91ab2d08f3c6Route,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sub-7e4c91ab2d08f3c6': typeof Sub7e4c91ab2d08f3c6RouteWithChildren
  '/vless': typeof VlessRoute
  '/api/stack': typeof ApiStackRoute
  '/sub-7e4c91ab2d08f3c6/links': typeof Sub7e4c91ab2d08f3c6LinksRoute
  '/sub-7e4c91ab2d08f3c6/sb.json': typeof Sub7e4c91ab2d08f3c6SbDotjsonRoute
  '/sub-7e4c91ab2d08f3c6/socks.txt': typeof Sub7e4c91ab2d08f3c6SocksDottxtRoute
  '/sub-7e4c91ab2d08f3c6/socks.yaml': typeof Sub7e4c91ab2d08f3c6SocksDotyamlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sub-7e4c91ab2d08f3c6': typeof Sub7e4c91ab2d08f3c6RouteWithChildren
  '/vless': typeof VlessRoute
  '/api/stack': typeof ApiStackRoute
  '/sub-7e4c91ab2d08f3c6/links': typeof Sub7e4c91ab2d08f3c6LinksRoute
  '/sub-7e4c91ab2d08f3c6/sb.json': typeof Sub7e4c91ab2d08f3c6SbDotjsonRoute
  '/sub-7e4c91ab2d08f3c6/socks.txt': typeof Sub7e4c91ab2d08f3c6SocksDottxtRoute
  '/sub-7e4c91ab2d08f3c6/socks.yaml': typeof Sub7e4c91ab2d08f3c6SocksDotyamlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sub-7e4c91ab2d08f3c6': typeof Sub7e4c91ab2d08f3c6RouteWithChildren
  '/vless': typeof VlessRoute
  '/api/stack': typeof ApiStackRoute
  '/sub-7e4c91ab2d08f3c6/links': typeof Sub7e4c91ab2d08f3c6LinksRoute
  '/sub-7e4c91ab2d08f3c6/sb.json': typeof Sub7e4c91ab2d08f3c6SbDotjsonRoute
  '/sub-7e4c91ab2d08f3c6/socks.txt': typeof Sub7e4c91ab2d08f3c6SocksDottxtRoute
  '/sub-7e4c91ab2d08f3c6/socks.yaml': typeof Sub7e4c91ab2d08f3c6SocksDotyamlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sub-7e4c91ab2d08f3c6'
    | '/vless'
    | '/api/stack'
    | '/sub-7e4c91ab2d08f3c6/links'
    | '/sub-7e4c91ab2d08f3c6/sb.json'
    | '/sub-7e4c91ab2d08f3c6/socks.txt'
    | '/sub-7e4c91ab2d08f3c6/socks.yaml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sub-7e4c91ab2d08f3c6'
    | '/vless'
    | '/api/stack'
    | '/sub-7e4c91ab2d08f3c6/links'
    | '/sub-7e4c91ab2d08f3c6/sb.json'
    | '/sub-7e4c91ab2d08f3c6/socks.txt'
    | '/sub-7e4c91ab2d08f3c6/socks.yaml'
  id:
    | '__root__'
    | '/'
    | '/sub-7e4c91ab2d08f3c6'
    | '/vless'
    | '/api/stack'
    | '/sub-7e4c91ab2d08f3c6/links'
    | '/sub-7e4c91ab2d08f3c6/sb.json'
    | '/sub-7e4c91ab2d08f3c6/socks.txt'
    | '/sub-7e4c91ab2d08f3c6/socks.yaml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Sub7e4c91ab2d08f3c6Route: typeof Sub7e4c91ab2d08f3c6RouteWithChildren
  VlessRoute: typeof VlessRoute
  ApiStackRoute: typeof ApiStackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sub-7e4c91ab2d08f3c6': {
      id: '/sub-7e4c91ab2d08f3c6'
      path: '/sub-7e4c91ab2d08f3c6'
      fullPath: '/sub-7e4c91ab2d08f3c6'
      preLoaderRoute: typeof Sub7e4c91ab2d08f3c6RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vless': {
      id: '/vless'
      path: '/vless'
      fullPath: '/vless'
      preLoaderRoute: typeof VlessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stack': {
      id: '/api/stack'
      path: '/api/stack'
      fullPath: '/api/stack'
      preLoaderRoute: typeof ApiStackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sub-7e4c91ab2d08f3c6/links': {
      id: '/sub-7e4c91ab2d08f3c6/links'
      path: '/links'
      fullPath: '/sub-7e4c91ab2d08f3c6/links'
      preLoaderRoute: typeof Sub7e4c91ab2d08f3c6LinksRouteImport
      parentRoute: typeof Sub7e4c91ab2d08f3c6Route
    }
    '/sub-7e4c91ab2d08f3c6/sb.json': {
      id: '/sub-7e4c91ab2d08f3c6/sb.json'
      path: '/sb.json'
      fullPath: '/sub-7e4c91ab2d08f3c6/sb.json'
      preLoaderRoute: typeof Sub7e4c91ab2d08f3c6SbDotjsonRouteImport
      parentRoute: typeof Sub7e4c91ab2d08f3c6Route
    }
    '/sub-7e4c91ab2d08f3c6/socks.txt': {
      id: '/sub-7e4c91ab2d08f3c6/socks.txt'
      path: '/socks.txt'
      fullPath: '/sub-7e4c91ab2d08f3c6/socks.txt'
      preLoaderRoute: typeof Sub7e4c91ab2d08f3c6SocksDottxtRouteImport
      parentRoute: typeof Sub7e4c91ab2d08f3c6Route
    }
    '/sub-7e4c91ab2d08f3c6/socks.yaml': {
      id: '/sub-7e4c91ab2d08f3c6/socks.yaml'
      path: '/socks.yaml'
      fullPath: '/sub-7e4c91ab2d08f3c6/socks.yaml'
      preLoaderRoute: typeof Sub7e4c91ab2d08f3c6SocksDotyamlRouteImport
      parentRoute: typeof Sub7e4c91ab2d08f3c6Route
    }
  }
}

interface Sub7e4c91ab2d08f3c6RouteChildren {
  Sub7e4c91ab2d08f3c6LinksRoute: typeof Sub7e4c91ab2d08f3c6LinksRoute
  Sub7e4c91ab2d08f3c6SbDotjsonRoute: typeof Sub7e4c91ab2d08f3c6SbDotjsonRoute
  Sub7e4c91ab2d08f3c6SocksDottxtRoute: typeof Sub7e4c91ab2d08f3c6SocksDottxtRoute
  Sub7e4c91ab2d08f3c6SocksDotyamlRoute: typeof Sub7e4c91ab2d08f3c6SocksDotyamlRoute
}

const Sub7e4c91ab2d08f3c6RouteChildren: Sub7e4c91ab2d08f3c6RouteChildren = {
  Sub7e4c91ab2d08f3c6LinksRoute: Sub7e4c91ab2d08f3c6LinksRoute,
  Sub7e4c91ab2d08f3c6SbDotjsonRoute: Sub7e4c91ab2d08f3c6SbDotjsonRoute,
  Sub7e4c91ab2d08f3c6SocksDottxtRoute: Sub7e4c91ab2d08f3c6SocksDottxtRoute,
  Sub7e4c91ab2d08f3c6SocksDotyamlRoute: Sub7e4c91ab2d08f3c6SocksDotyamlRoute,
}

const Sub7e4c91ab2d08f3c6RouteWithChildren =
  Sub7e4c91ab2d08f3c6Route._addFileChildren(Sub7e4c91ab2d08f3c6RouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Sub7e4c91ab2d08f3c6Route: Sub7e4c91ab2d08f3c6RouteWithChildren,
  VlessRoute: VlessRoute,
  ApiStackRoute: ApiStackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
